Lock pytest<3.3.0 due to strange bug
pytest 3.3.0 was released less than a week ago. Running it under our
current docker image (at least for Python 3) produces this mystifying
error:

  ImportError: No module named '_pytest._pluggy'

Simplest fix is to lock to older pytest versions until we figure this
out.