Fix crash when adding devices with duplicate serial numbers.  Reported by Joshua Sidwell:
---
Mod_python error: "PythonHandler editdb"

Traceback (most recent call last):

  File "/usr/lib/python2.3/site-packages/mod_python/apache.py", line 299, in HandlerDispatch
    result = object(req)

  File "/usr/local/nav/apache/webroot/editdb/editdb.py", line 156, in handler
    output = editPage(req,pageList[table](),request,unicodeError)

  File "/usr/local/nav/apache/webroot/editdb/editdb.py", line 463, in editPage
    outputForm,action)

  File "/usr/local/nav/apache/webroot/editdb/editdb.py", line 2435, in add
    disabled=True))

TypeError: __init__() takes at least 2 non-keyword arguments (1 given)
---

 * editdb.py
   (pageNetbox.editboxCategoy.add): Add the missing argument when
   calling pageNetbox.editbox